### ISSUE TITLE
Poner anotación @Temporal

### ISSUE THREAD

**Issue by Lainezz** [Joakamakaka1/ProyectoStockControl#1]
https://github.com/Joakamakaka1/ProyectoStockControl/blob/0d44dde0fd00828ed30cd75bd25a7e91c9a656fe/src/main/java/com/es/stockcontrol/model/Producto.java#L24

Mejora la anotación de ese atributo de clase. Recuerda la anotación @Temporal

**Comment by Joakamakaka1** [comment]
Corregido @Lainezz
