### ISSUE TITLE
Atributo private

### ISSUE THREAD

**Issue by Lainezz** [Joakamakaka1/ProyectoStockControl#2]
https://github.com/Joakamakaka1/ProyectoStockControl/blob/0d44dde0fd00828ed30cd75bd25a7e91c9a656fe/src/main/java/com/es/stockcontrol/model/Proveedor.java#L19

Cambia la visibilidad a private

**Comment by PabloGonz68** [comment]
Ya están corregidos los cambios @Lainezz ✅
